---
 - hosts: dev
   tasks: 
   - name: pull the image from Docker rigistry
     raw: docker pull meghanath/test:1
   - name: Remove the container if present
     raw: docker rm -f c1
     ignore_errors: true
   - name: spin up container
     raw: docker run -dti --name c1 -p 99:80 meghanath/test:1 /bin/bash
