---
 - hosts: dev
   tasks: 
   - name: pull the image from Docker rigistry
     raw: docker pull meghanath/test1:2
   - name: Remove the container if present
     raw: docker rm -f c2
     ignore_errors: true
   - name: spin up container
     raw: docker run -dti --name c2 -p 98:80 meghanath/test1:2 /bin/bash

 - hosts: qa
   tasks:
   - name: pull the image from Docker rigistry
     raw: docker pull meghanath/test2:2
   - name: Remove the container if present
     raw: docker rm -f c2
     ignore_errors: true
   - name: spin up container
     raw: docker run -dti --name c2 -p 98:80 meghanath/test2:2 /bin/bash

